export class Remark
{
    remarkId:number;
	templateId:number;
	groupId:number;
	totalRange:number;
    range1:string;
	comment1:string;
	range2:string;
	comment2:string;
	range3:string;
	comment3:string;
	range4:string;
	comment4:string;
	range5:string;
	comment5:string;
	range6:string;
	comment6:string;
	range7:string;
	comment7:string;
	range8:string;
	comment8:string;
	range9:string;
	comment9:string;
	range10:string;
	comment10:string;
	range11:string;
	comment11:string;
	range12:string;
	comment12:string;
	range13:string
	comment13:string;
	range14:string;
	comment14:string;
	range15:string;
	comment15:string;
	range16:string;
	comment16:string;
	range17:string;
	comment17:string;
	range18:string;
	comment18:string;
	range19:string;
	comment19:string;
	range20:string;
	comment20:string;
	timestamp:Date;
}