export const formConfig = {
    country: {
        options : ['Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda','Argentina','Armenia','Australia','Austria','Azerbaijan','Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize','Benin','Bhutan','Bolivia (Plurinational State of)','Bosnia and Herzegovina','Botswana','Brazil','Brunei Darussalam','Bulgaria','Burkina Faso','Burundi','Cabo Verde','Cambodia','Cameroon','Canada','Central African Republic','Chad','Chile','China','Colombia','Comoros','Congo','Cook Islands','Costa Rica','Croatia','Cuba','Cyprus','Czechia','Côte dIvoire','Democratic Peoples Republic of Korea','Democratic Republic of the Congo','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Faroe Islands','Fiji','Finland','France','Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea-Bissau','Guyana','Haiti','Honduras','Hungary','Iceland','India','Indonesia',
                  'Iran (Islamic Republic of)','Iraq','Ireland','Israel','Italy','Jamaica','Japan','Jordan','Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan','Lao Peoples Democratic Republic','Latvia','Lebanon','Lesotho','Liberia','Libya','Lithuania','Luxembourg','Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','MarshallIslands','Mauritania','Mauritius','Mexico','Micronesia (Federated States of)','Monaco','Mongolia','Montenegro','Morocco','Mozambique','Myanmar','Namibia','Nauru','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria','Niue','North Macedonia','Norway','Oman','Pakistan','Palau','Panama','Papua New Guinea','Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Republic of Korea','Republic of Moldova','Romania','Russian Federation','Rwanda','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','San Marino','Sao Tome and Principe','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone','Singapore','Slovakia','Slovenia','Solomon Islands','Somalia','South Africa','South Sudan','Spain','Sri Lanka','Sudan','Suriname','Sweden','Switzerland','Syrian Arab Republic','Tajikistan','Thailand','Timor-Leste','Togo','Tokelau','Tonga','Trinidad and Tobago','Tunisia','Turkey','Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom of Great Britain and Northern Ireland','United Republic of Tanzania','United States of America','Uruguay','Uzbekistan','Vanuatu','Venezuela (Bolivarian Republic of)','Viet Nam','Yemen','Zambia','Zimbabwe','share'],
      },
      state : {
        options : ['Andaman_And_nicobar_islands','Andhra_Pradesh','Arunachal_Pradesh','Assam','Bihar','Chandigarh','Chhattisgarh','Dadar_And_Nagar_Haveli','Daman_And_Diu','Delhi','Goa','Gujrat','Haryan','Himachal_Pradesh','Jammu_And_kashmir','Jharkhand','Karnataka','Kerala','Lakshwadweep','Madhya_Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Pondicherry','Punjab','Rajasthan','Sikkim','Tamil_Nadu','Telangana','Tripura','UttarPradesh','Uttarakhand','West Bangal'],         
      },
      city : {
        options:[],
        Andaman_And_nicobar_islands : ['Nicobar','North And middle andaman','South Andaman'],
        Andhra_Pradesh : ['Anantapur','Chittoor','Cuddapah','East Godavari','Guntur','Krishna','Kurnool','Nellore','Prakasam','Shrikakulam','Visakhapatnam','Vizianagaram','West Godavari'],
        Arunachal_Pradesh : ['Changlang','Dibang Valley','East Kameng','East Siang','Kurung Kumey','Lohit','Lower Dibang Valley','Lower Sabansiri','Papum Pare','Tawang','Tirap','Upper Siang','Upper Subansiri','West Kameng','West Siang'],
        Assam : ['Barpeta','Bongaigaon','Cachar','Darrang','Dhemaji','Dhubri','Dibrugarh','Goalpara','Golaghat','Hailakandi','Jorhat','Kamrup','Karbi Anglong','Karimganj','Kokrajhar','Lakhimpur','Marigaon','Nagaon','Nalbari','North Cachar hills','Sivasagar Sibsagar','Sonitpur','Tinsukia'],
        Bihar : ['Araria','Aurangabad','Banka','Begusarai','Bhagalpur','Bhojpur','Buxar','Darbhanga','East Champaran','Gaya','Gopalganj','Jamui','Jehanabad',
                'Kaimur (bhabua)','Katihar','Khagaria','Kishanganj','Lakhisarai','Madhepura','Madhubani','Munger','Muzaffarpur','Nalanda','Nawada','Patna','Purnia','Rohtas','Saharsa','Samastipur','Saran','Sheikhpura','Sheohar','Sitamarhi',
                'Siwan','Supaul','Vaishali','West Champaran'],
        Chandigarh : ['Chandigarh'],
        Chhattisgarh : ['Bastar','Bijapur','Bilaspur','Dantewada','Dhamtari','Durg','Janjgir-champa','Jashpur','Kanker','Kawardha','Korba','Koriya','Mahasamund','Narayanpur','Raigarh','Raipur','Rannandgaon','Surguja'],
        Dadar_And_Nagar_Haveli : ['Dadar and Nagar Haveli'],
        Daman_And_Diu : ['Daman','Diu'],
        Delhi : ['Central Delhi','East Delhi','New Delhi','North Delhi','North West Delhi','South Delhi','South West Delhi','West Delhi'],
        Goa : ['North Goa','South Goa'],
        Gujrat : ['Ahmedabad','Amreli','Anand','Banaskantha','Bharuch','Bhavnagar','Dahod','Gandhi Nagar','Jamnagar','Junagadh','Kachchh','Kheda','Mahesana','Narmada','Navsari','Panch Mahals','Patan','Porbandar','Rajkot','Sabarkantha','Surat','Surendra Nagar','The Dangs','Vadodara','Valsad'],
        Haryan : ['Ambala','Bhiwani','Faridabad','Fatehabad','Gurgaon','Hisar','Jhajjar','Jind','Kaithal','Karnal','Kurukshetra','Mahendragarh','Panchkula','Panipat','Rewari','Rohtak','Sirsa','Sonipat','Yamuna Nagar'],
        Himachal_Pradesh : ['Bilaspur','Chamba','Hamirpur','Kangra','Kinnaur','Kullu','Lahul and Spiti','Mandi','Shimla','Sirmaur','Solan','Una'],
        Jammu_And_kashmir : ['Ananthnag','Baramulla','Budgam','Doda','Kargil','Kathua','Kupwara','Leh','Poonch','Pulwama','Rajauri','Samba','Srinagar','Udhampur'],
        Jharkhand :['Bokaro','Chatra','Deoghar','Dhanbad','Dumka','East Singhbhum','Garhwa','Giridh','Godda','Gumla','Hazaribag','Jamtara','Koderma','Latehar','Lohardaga','Pakur','Palamau','Ramgarh','Ranchi','Sahibganj','Seraikela-kharsawan','Simdega','West Singhbhum'],
        Karnataka : ['Bagalkot','Bangalore Rural','Bangalore','Belgaum','Bellary','Bidar','Bijapur','Chamrajnagar','Chickmagalur','Chitradurga','Dakshina Kannada','Davangare','Dharward','Gadag','Gulbarga','Haveri','Kodagu','Kolar','Koppal','Mandya','Mysore','Raichur','Shimoga','Tumkur','Udupi','Uttara Kannada'],
        Kerala : ['Alappuzha','Emakulam','Idukki','Kannur','Kasargod','Kollam','Kottayam','Kozhikode','Malappuram','Palakkad','Pathanamthitta','Thiruvananthapuram','Thrissur','Wayanad'],
        Lakshwadweep : ['Lakshwadweep'],
        Madhya_Pradesh : ['Anuppur','Ashoknagar','Balaghat','Barwani','Betul','Bhind','Bhopal','Burhanpur','Chhatarpur','Chhindwara','Damoh','Datia','Dewas','Dhar','Dindori','Guna','Gwalior','Harda','Hoshangabad','Indore','Jabalpur','Jhabua','Katni','Khandwa East nimar','Khargone Westnimar','Mandla','Mandsaur','Morena','Narsinghpur','Neemuch','Panna','Raisen','Rajgarh','Ratlam','Rewa','Sagar','Satna','Sehore','Seoni','Shahdol','Shajapur','Sheopur','Shivpuri','Sidhi','Tikamgarh','Ujjain','Umari','Vidisha'],
        Maharashtra : ['Ahmednagar','Akola','Aurangabad','Beed','Bhandara','Buldhana','Chandrapur','Dhule','Gadchiroli','Gondia','Hingoli','Jalgaon','Jalna','Kolhapur','Latur','Mumbai','Nagpur','Nanded','Nandurbar','Nashik','Osmanabad','Parbhani','Pune','Raigad','Ratnagiri','Sangli','Satara','Sindhudurg','Solapur','Thane','Wardha','Washim','Yavatmal'],
        Manipur : ['Bishnupur','Chandel','Churachandpur','Imphal East','Imphal West','Senapati','Tamenglong','Thoubal','Ukhrul'],
        Meghalaya : ['East Garo Hills','East Khasi Hills','Jaintia Hills','Ri Bhoi','South Garo Hills','West Garo Hills','West Khasi Hills'],
        Mizoram : ['Aizawl','Champhai','Kolasib','Lawngtlai','Lunglei','Mammit','Saiha','Serchhip'],
        Nagaland : ['Dimapur.','Kiphire','Kohima','Longleng','Mokokchung','Mon','Peren','Phek','Tuensang','Wokha','Zunhebotto'],
        Odisha : ['Angul','Balangir','Baleswar','Bargarh','Bhadrak','Boudh','Cuttack','Debagarh Deogarh','Dhenkanal','Gajapati','Ganjam','Jagatsinghapur','Jajapur','Jharsuguda','Kalahandi','Kandhamal','Kendrapara','Kendujhar','Khurda Khorda','Koraput','Malkangiri','Mayurbhanj','Nabarangapur','Naupada','Nayagarh','Puri','Rayagada','Sambalpur','Sonapur Subarnagar','Sundergarh'],
        Pondicherry : ['Karaikal','Mahe','Pondicherry'],
        Punjab : ['Amritsar','Bathinda','Faridkot','Fatehgarh Sahib','Firozpur','Gurdaspur','Hoshiarpur','Jalandhar','Kapurthala','Ludhiana','Mansa','Moga','Mohali','Muktsar','Nawanshahr','Patiala','Ropar Rupnagar','Sangrur'],
        Rajasthan : ['Ajmer','Alwar','Banswara','Baran','Barmer','Bharatpur','Bhilwara','Bikaner','Bundi','Chittorgarh','Churu','Dausa','Dholpur','Dungarpur','Hanumangarh','Jaipur','Jaisalmer','Jalor','Jhalawar','Jhunjhunu','Jodhpur','Karauli','Kota','Nagaur','Pali','Rajsamand','Sawai Madhopur','Sikar','Sirohi','Sri Ganganagar','Tonk','Udaipur','Nawanshahr','Patiala','Ropar Rupnagar','Sangrur'],
        Sikkim : ['East Sikkim','North Sikkim','South Sikkim','West Sikkim'],
        Tamil_Nadu : ['Ariyayalur','Chennai','Coimbatore','Cuddalore','Dharampuri','Dindigul','Erode','Kanchipuram','Kanyakumari','Karur','Krishnagiri','Madhurai','Nagapattinam','Namakkal','Nilgiris','Perambalur','Pudukkottai','Ramanathapuram','Selam','Shivganga','Thanjavur','Theni','Tiruchirappalli','Tirunelveli','Tiruvallur','Tiruvannamalai','Tiruvarur','Tuticorin Thoothukudi','Vellore','Vidhunagar','Villupuram'],
        Telangana : ['Adilabad','Hyderabad','Karim Nagar','Khammam','Mahabubnagar','Medak','Naigonda','Nizamabad','Rangareddi','Warangal'],
        Tripura : ['Dhalai','North Tripura','South Tripura','West Tripura'],
        UttarPradesh : ['Agra','Aligarh','Allahabad','Ambedkar Nagar','Auraiya','Azamgarh','Bagpat','Ballia','Balrampur','Banda','Barabanki','Bareilly','Basti','Behraich','Bijnor','Budaun','Bulandshahr','Chandauli','Chitrakoot','Deoria','Etah','Etawah','Faizabad','Farrukhabad','Fatehpur','Firozabad','Gautam Buddha Nagar','Ghaziabad','Ghazipur','Gonda','Gorakhpur','Hamirpur','Hardoi','Hathras','Jalaun','Jaunpur','Jhansi','Jyotiba Phule Nagar','Kannauj','Kanpur Dehat','Kanpur Nagar','Kaushambi','Kheri','Kushinagar','Lalitpur','Lucknow','Maharajganj','Mahoba','Mainpuri','Mathura','Mau','Meerut','Mirzapur','Moradabad','Muzaffarnagar','Pilibhit','Pratapgarh','Raebareli','Rampur','Saharanpur','Sant Kabir Nagar','Sant Ravidas Nagar','Shahjahanpur','Shrawasti','SiddharthNagar','Sitapur','Sonbhadra','Sultanpur','Unnao','Varanasi'],
        Uttarakhand : ['Almora','Bageshwar','Chamoli','Champawat','Dehradun','Haridwar','Nainital','Pauri Garhwal','Pithoragarh','Rudraprayag','Tehri Garhwal','Udham Singh Nagar','Uttarkashi'],
        West_Bangal : ['Bankura','Bardhaman','Birbhum','Cooch Behar','Darjeeling','East Medinipur','Hooghly','Howrah','Jalpaiguri','Kolkata','Malda','Murshidabad','Nadia','North 24 Parganas','North Dinajpur uttar','Purulia','South 24 Paraganas','South Dinajpur','West Medinipur','West Midnapore'],
      },
      category : {
        options : ['Student','Parent','Teacher','Other'],
      },
      education : {
        options : ['No Formal Education','Primary','Pre-Primary','1st standard','2nd standard','3rd standard','4th standard','5th standard','6th standard','7th standard','8th standard','9th standard','10th standard','Senior-Secondary','Diploma','Graduate','Postgraduate','Other'],
      },
      gender : {
        options : ['Male','Female','Other'],
      },
      languages : {
        options : ['English','Marathi','Hindi'],
      },
  
};